### ISSUE TITLE
micb function errors

### ISSUE THREAD

**Issue by di-zhou** [datadiarist/lorenz#2]
Hi! When I run the `mcib` function sample code given in the [package vignette](https://cran.r-project.org/web/packages/lorenz/lorenz.pdf):

```
ex_freqs <- c(45, 31, 33, 27, 43, 40, 51, 50, 63, 97, 121, 132, 64, 54, 32, 12)
ex_bounds <- c(0, 10000, 15000, 20000, 25000, 30000, 35000, 40000, 45000, 50000,
     60000, 75000, 100000, 125000, 150000, 200000)
ex_mean <- 66500
mcib(ex_freqs, ex_bounds, ex_mean)
```

I got the following error message:

```
Error in mcib(ex_freqs, ex_bounds, ex_mean) : 
  could not find function "mcib"
```

I can run the sample code for the `lorenz_interp` with no problem. I wonder if you can check if the code for `mcib` is uploaded? Thank you!

My session info:

```
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.3

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib
```

**Comment by AndrewCarr24** [comment]
Hey! The development version of the lorenz package no longer includes the MCIB function because I had found some small differences between the numbers produced by my implementation of MCIB and the numbers from the original STATA version. I'd recommend using the STATA version. I do plan on fixing my implementation at some point down the road.

If you want to run my implementation of MCIB, the mcib function is still available through the CRAN version of lorenz.

**Comment by di-zhou** [comment]
Thank you!
